#pragma once

#include "Common.h"

enum ColorId : uchar {
	RED = 0, BLUE, YELLOW, GREEN, WHITE_REM, ORANGE, DARKGREY, GREY, LIGHTGREY, BROWN, WHITE, LIGHTBLUE, LIME, MAROON, DARKBLUE, DARKGREEN,
	BEIGE, PINK, LIGHTYELLOW, LIGHTORANGE, SANDBLUE, SANDGREEN
};