#include "World.h"
using namespace std;

ostream& operator<<(ostream& out, const ZoneId value) {
#define WRITE_ELEMENT(p) case p: return out << #p;

	switch (value) {
		WRITE_ELEMENT(VENTURE_EXPLORER) WRITE_ELEMENT(VENTURE_EXPLORER_RETURN)
		WRITE_ELEMENT(AVANT_GARDENS)
		WRITE_ELEMENT(NIMBUS_STATION) WRITE_ELEMENT(NIMBUS_ROCK) WRITE_ELEMENT(NIMBUS_ISLE)
		WRITE_ELEMENT(PET_COVE)
		WRITE_ELEMENT(GNARLED_FOREST)
		WRITE_ELEMENT(FORBIDDEN_VALLEY)
		WRITE_ELEMENT(STARBASE_3001)
		WRITE_ELEMENT(DEEP_FREEZE)
		WRITE_ELEMENT(ROBOT_CITY)
		WRITE_ELEMENT(MOON_BASE)
		WRITE_ELEMENT(PORTABELLO)
		WRITE_ELEMENT(CRUX_PRIME)
		WRITE_ELEMENT(NEXUS_TOWER)
		WRITE_ELEMENT(NINJAGO_MONASTERY)
		default: return out << "UNKNOW_ZONE with id: " << (int)value;
	}

#undef WRITE_ELEMENT
}